// Package envexport writes .env files for the mdp orchestrator.
//
// Two flavors exist:
//   - Per-service: the exact env passed to a service's process.
//   - Global: an explicit user-defined map, with values resolved via
//     envexpand so they can reference other services.
package envexport

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/derekgould/multi-dev-proxy/internal/config"
	"github.com/derekgould/multi-dev-proxy/internal/envexpand"
)

const header = "# Generated by mdp — do not edit. Overwritten on start.\n"

// WritePerService writes a .env file containing the given KEY=VALUE entries.
// The env slice is in "KEY=VALUE" form (same shape as os/exec's Cmd.Env).
// Keys are sorted alphabetically for deterministic diffs.
func WritePerService(path string, env []string) error {
	pairs := make(map[string]string, len(env))
	for _, kv := range env {
		k, v, ok := splitKV(kv)
		if !ok {
			continue
		}
		pairs[k] = v
	}
	return writeFile(path, pairs)
}

// WriteGlobal resolves each entry in globalEnv against pm/em and writes the
// result to path. Cross-repo @-references are not supported; use
// WriteGlobalWith to enable them.
func WriteGlobal(path string, globalEnv map[string]config.EnvValue, pm envexpand.PortMap, em envexpand.EnvMap) error {
	return WriteGlobalWith(path, globalEnv, pm, em, nil)
}

// WriteGlobalWith is WriteGlobal with a Resolver for cross-repo @-references.
// Unresolved cross-repo refs without a default are omitted from the output
// (graceful degradation); unresolved local refs without a default error.
func WriteGlobalWith(path string, globalEnv map[string]config.EnvValue, pm envexpand.PortMap, em envexpand.EnvMap, resolver envexpand.Resolver) error {
	pairs := make(map[string]string, len(globalEnv))
	for k, entry := range globalEnv {
		if entry.Ref != "" {
			val, err := envexpand.LookupRefWith(entry.Ref, entry.DefaultValue(), entry.HasDefault(), pm, em, resolver)
			if err != nil {
				if entry.HasDefault() {
					pairs[k] = entry.DefaultValue()
					continue
				}
				if envexpand.IsCrossRepoBareRef(entry.Ref) {
					continue // omit unresolved cross-repo refs without default
				}
				return fmt.Errorf("global env %q: %w", k, err)
			}
			pairs[k] = val
			continue
		}
		val, err := envexpand.ExpandWith(entry.Value, pm, em, resolver)
		if err != nil {
			return fmt.Errorf("global env %q: %w", k, err)
		}
		pairs[k] = val
	}
	return writeFile(path, pairs)
}

func writeFile(path string, pairs map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}
	keys := make([]string, 0, len(pairs))
	for k := range pairs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString(header)
	for _, k := range keys {
		b.WriteString(k)
		b.WriteString("=\"")
		b.WriteString(escape(pairs[k]))
		b.WriteString("\"\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// escape prepares a value for inclusion inside double-quoted dotenv syntax.
func escape(v string) string {
	var b strings.Builder
	b.Grow(len(v))
	for _, r := range v {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

func splitKV(kv string) (string, string, bool) {
	i := strings.IndexByte(kv, '=')
	if i < 0 {
		return "", "", false
	}
	return kv[:i], kv[i+1:], true
}
