# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  name "mdp"
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  on_macos do
    on_intel do
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_amd64.tar.gz"
      sha256 "d28eacb8cd00994d551097a6de5172f3c5035ea98478a0e9b8337cf483499618"
    end
    on_arm do
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_arm64.tar.gz"
      sha256 "3328ba32db6fdfa995568fedee47b76c59e71bc81d76b8d1a60beb8ff76dbca8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_amd64.tar.gz"
      sha256 "05487aa57b8840ad32ae6cd0af65c395d6bad0391aa1151fcfff48059741d520"
    end
    on_arm do
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_arm64.tar.gz"
      sha256 "ef538b9daa3e5478f21e56ede6f0fc895ad2b17281b2d5aafc1ca629c3669223"
    end
  end

  # No zap stanza required
end
